version: "3.6"

services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "container_logs"
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp # optional
      - 8843:8843 # optional
      - 8880:8880 # optional
      - 6789:6789 # optional
      - 5514:5514/udp # optional
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Stockholm"
      MEM_LIMIT: 1024 # optional
      MEM_STARTUP: 1024 # optional
    volumes:
      - type: bind
        source: ./config
        target: /config
