version: "3.6"

services:
  portainer:
    image: portainer/portainer-ce:2.18.1
    container_name: portainer
    labels:
      logging: "promtail"
      logging_jobname: "container_logs" 
      com.centurylinklabs.watchtower.monitor-only: true
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./data
        target: /data
