version: "3.6"

services:
  portainer:
    image: portainer/portainer-ce:2.16.2
    container_name: portainer
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./data
        target: /data
